/* Generated By:JavaCC: Do not edit this line. VCPU32ParserTokenManager.java */
package yuxuanchiadm.apc.vcpu32.asm.parser;
import java.io.StringReader;
import yuxuanchiadm.apc.vcpu32.asm.parser.visitor.*;
import yuxuanchiadm.apc.vcpu32.asm.parser.syntaxtree.*;

/** Token Manager. */
@SuppressWarnings("all")
public class VCPU32ParserTokenManager implements VCPU32ParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 44:
         return jjStopAtPos(0, 19);
      case 58:
         return jjStopAtPos(0, 16);
      case 91:
         return jjStopAtPos(0, 17);
      case 93:
         return jjStopAtPos(0, 18);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec3 = {
   0x1ff00000fffffffeL, 0xffffffffffffc000L, 0xffffffffL, 0x600000000000000L
};
static final long[] jjbitVec4 = {
   0x0L, 0x0L, 0x0L, 0xff7fffffff7fffffL
};
static final long[] jjbitVec5 = {
   0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec6 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffL, 0x0L
};
static final long[] jjbitVec7 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L, 0x0L
};
static final long[] jjbitVec8 = {
   0x3fffffffffffL, 0x0L, 0x0L, 0x0L
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 157;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 26);
                  else if ((0x100002600L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 45)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 36)
                  {
                     if (kind > 15)
                        kind = 15;
                     jjCheckNAdd(53);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(4, 6);
                  else if (curChar == 39)
                     jjAddStates(7, 8);
                  else if (curChar == 46)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAdd(27);
                  }
                  else if (curChar == 59)
                  {
                     if (kind > 2)
                        kind = 2;
                     jjCheckNAdd(2);
                  }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAdd(29);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAddTwoStates(152, 154);
                  }
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(30, 31);
                  break;
               case 0:
                  if ((0x100002600L & l) == 0L)
                     break;
                  if (kind > 1)
                     kind = 1;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAdd(2);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 26);
                  break;
               case 26:
                  if (curChar != 46)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(27);
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(27);
                  break;
               case 28:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(29);
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(29);
                  break;
               case 30:
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(30, 31);
                  break;
               case 32:
                  if (curChar == 39)
                     jjAddStates(7, 8);
                  break;
               case 34:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(35);
                  break;
               case 35:
                  if (curChar == 39 && kind > 13)
                     kind = 13;
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(35);
                  break;
               case 41:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAdd(35);
                  break;
               case 42:
                  if (curChar == 34)
                     jjCheckNAddStates(4, 6);
                  break;
               case 44:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 45:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 46:
                  if (curChar == 34 && kind > 14)
                     kind = 14;
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 52:
                  if (curChar != 36)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAdd(53);
                  break;
               case 53:
                  if ((0x3ff001000000000L & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAdd(53);
                  break;
               case 151:
                  if (curChar != 48)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAddTwoStates(152, 154);
                  break;
               case 153:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 154:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(154);
                  break;
               case 155:
                  if (curChar == 45)
                     jjCheckNAddStates(0, 3);
                  break;
               case 156:
                  if (curChar == 48 && kind > 10)
                     kind = 10;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 15)
                        kind = 15;
                     jjCheckNAdd(53);
                  }
                  if ((0x700860eL & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                  }
                  else if (curChar == 83)
                     jjAddStates(9, 17);
                  else if (curChar == 80)
                     jjAddStates(18, 20);
                  else if (curChar == 82)
                     jjAddStates(21, 22);
                  else if (curChar == 71)
                     jjAddStates(23, 27);
                  else if (curChar == 77)
                     jjAddStates(28, 30);
                  else if (curChar == 70)
                     jjAddStates(31, 40);
                  else if (curChar == 68)
                     jjAddStates(41, 45);
                  else if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 18;
                  else if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 8;
                  if (curChar == 79)
                     jjAddStates(46, 47);
                  else if (curChar == 65)
                     jjAddStates(48, 50);
                  else if (curChar == 67)
                     jjAddStates(51, 53);
                  else if (curChar == 73)
                     jjCheckNAddStates(54, 60);
                  else if (curChar == 74)
                     jjstateSet[jjnewStateCnt++] = 22;
                  else if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 2:
                  if (kind > 2)
                     kind = 2;
                  jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 3:
                  if (curChar == 82 && kind > 6)
                     kind = 6;
                  break;
               case 4:
               case 20:
                  if (curChar == 79)
                     jjCheckNAdd(3);
                  break;
               case 5:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 80 && kind > 6)
                     kind = 6;
                  break;
               case 7:
                  if (curChar == 77)
                     jjCheckNAdd(6);
                  break;
               case 8:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 10:
                  if (curChar == 75 && kind > 6)
                     kind = 6;
                  break;
               case 11:
               case 14:
               case 56:
               case 103:
               case 116:
               case 126:
                  if (curChar == 67)
                     jjCheckNAdd(10);
                  break;
               case 12:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 15:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 84 && kind > 6)
                     kind = 6;
                  break;
               case 18:
                  if (curChar == 88)
                     jjCheckNAdd(17);
                  break;
               case 19:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 21:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
               case 123:
                  if (curChar == 83)
                     jjCheckNAdd(3);
                  break;
               case 23:
                  if (curChar == 74)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if ((0x700860eL & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 31:
                  if (curChar == 66 && kind > 12)
                     kind = 12;
                  break;
               case 33:
                  if (curChar == 92)
                     jjAddStates(61, 62);
                  break;
               case 34:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(35);
                  break;
               case 36:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAdd(35);
                  break;
               case 41:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(35);
                  break;
               case 43:
                  if (curChar == 92)
                     jjAddStates(63, 64);
                  break;
               case 44:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 45:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 47:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 52:
               case 53:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAdd(53);
                  break;
               case 54:
                  if (curChar == 68)
                     jjAddStates(41, 45);
                  break;
               case 55:
                  if (curChar == 85)
                     jjCheckNAdd(6);
                  break;
               case 57:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 86 && kind > 6)
                     kind = 6;
                  break;
               case 59:
               case 74:
                  if (curChar == 73)
                     jjCheckNAdd(58);
                  break;
               case 60:
               case 63:
               case 147:
                  if (curChar == 65)
                     jjCheckNAdd(17);
                  break;
               case 61:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 64:
                  if (curChar == 70)
                     jjAddStates(31, 40);
                  break;
               case 65:
                  if (curChar == 68 && kind > 6)
                     kind = 6;
                  break;
               case 66:
               case 108:
                  if (curChar == 79)
                     jjCheckNAdd(65);
                  break;
               case 67:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 65 && kind > 6)
                     kind = 6;
                  break;
               case 69:
               case 94:
                  if (curChar == 70)
                     jjCheckNAdd(68);
                  break;
               case 70:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 66 && kind > 6)
                     kind = 6;
                  break;
               case 72:
               case 143:
                  if (curChar == 85)
                     jjCheckNAdd(71);
                  break;
               case 73:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 75:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 76 && kind > 6)
                     kind = 6;
                  break;
               case 77:
               case 109:
                  if (curChar == 85)
                     jjCheckNAdd(76);
                  break;
               case 78:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 73 && kind > 6)
                     kind = 6;
                  break;
               case 80:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
               case 124:
                  if (curChar == 68)
                     jjCheckNAdd(65);
                  break;
               case 82:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 85 && kind > 6)
                     kind = 6;
                  break;
               case 84:
               case 95:
                  if (curChar == 70)
                     jjCheckNAdd(83);
                  break;
               case 85:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 78 && kind > 6)
                     kind = 6;
                  break;
               case 87:
               case 100:
                  if (curChar == 70)
                     jjCheckNAdd(86);
                  break;
               case 88:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 69 && kind > 6)
                     kind = 6;
                  break;
               case 90:
               case 93:
                  if (curChar == 70)
                     jjCheckNAdd(89);
                  break;
               case 91:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 73)
                     jjCheckNAddStates(54, 60);
                  break;
               case 96:
                  if (curChar == 70 && kind > 6)
                     kind = 6;
                  break;
               case 97:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 83 && kind > 6)
                     kind = 6;
                  break;
               case 99:
                  if (curChar == 78)
                     jjCheckNAdd(98);
                  break;
               case 101:
                  if (curChar == 67)
                     jjAddStates(51, 53);
                  break;
               case 102:
                  if (curChar == 82)
                     jjCheckNAdd(17);
                  break;
               case 104:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 76)
                     jjCheckNAdd(76);
                  break;
               case 106:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 77)
                     jjAddStates(28, 30);
                  break;
               case 110:
               case 136:
                  if (curChar == 79)
                     jjCheckNAdd(6);
                  break;
               case 111:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 71)
                     jjAddStates(23, 27);
                  break;
               case 113:
                  if (curChar == 72 && kind > 6)
                     kind = 6;
                  break;
               case 114:
                  if (curChar == 84)
                     jjCheckNAdd(113);
                  break;
               case 115:
                  if (curChar == 68)
                     jjCheckNAdd(17);
                  break;
               case 117:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 80)
                     jjCheckNAdd(76);
                  break;
               case 119:
                  if (curChar == 79 && kind > 6)
                     kind = 6;
                  break;
               case 120:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if (curChar == 65)
                     jjAddStates(48, 50);
                  break;
               case 122:
                  if (curChar == 78)
                     jjCheckNAdd(65);
                  break;
               case 125:
                  if (curChar == 82)
                     jjAddStates(21, 22);
                  break;
               case 127:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
               case 144:
                  if (curChar == 69)
                     jjCheckNAdd(17);
                  break;
               case 129:
                  if (curChar == 79)
                     jjAddStates(46, 47);
                  break;
               case 130:
                  if (curChar == 84)
                     jjCheckNAdd(98);
                  break;
               case 131:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 85)
                     jjCheckNAdd(17);
                  break;
               case 133:
                  if (curChar == 80)
                     jjAddStates(18, 20);
                  break;
               case 134:
                  if (curChar == 83)
                     jjCheckNAdd(113);
                  break;
               case 135:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 137:
                  if (curChar == 67 && kind > 7)
                     kind = 7;
                  break;
               case 138:
                  if (curChar == 83)
                     jjAddStates(9, 17);
                  break;
               case 139:
                  if (curChar == 72)
                     jjCheckNAdd(3);
                  break;
               case 140:
                  if (curChar == 65)
                     jjCheckNAdd(6);
                  break;
               case 141:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 72)
                     jjCheckNAdd(76);
                  break;
               case 145:
                  if (curChar == 76)
                     jjCheckNAdd(17);
                  break;
               case 146:
                  if (curChar == 84)
                     jjCheckNAdd(17);
                  break;
               case 148:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 80 && kind > 7)
                     kind = 7;
                  break;
               case 152:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(153);
                  break;
               case 153:
                  if ((0x7eL & l) == 0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  jjCheckNAdd(153);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 53:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 15)
                     kind = 15;
                  jjCheckNAdd(53);
                  break;
               case 2:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 41:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 45:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(4, 6);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 157 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   25, 26, 28, 156, 43, 45, 46, 33, 41, 139, 141, 142, 143, 144, 145, 146, 
   149, 150, 135, 136, 137, 127, 128, 114, 115, 117, 118, 120, 108, 109, 111, 67, 
   70, 73, 75, 78, 80, 82, 85, 88, 91, 55, 57, 59, 62, 63, 131, 132, 
   122, 123, 124, 102, 104, 106, 93, 94, 95, 97, 99, 100, 86, 34, 36, 44, 
   47, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec4[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec5[i2] & l2) != 0L);
      case 49:
         return ((jjbitVec6[i2] & l2) != 0L);
      case 51:
         return ((jjbitVec7[i2] & l2) != 0L);
      case 61:
         return ((jjbitVec8[i2] & l2) != 0L);
      default :
         if ((jjbitVec3[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, "\72", "\133", "\135", "\54", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfffc1L, 
};
static final long[] jjtoSkip = {
   0x6L, 
};
static final long[] jjtoSpecial = {
   0x6L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[157];
private final int[] jjstateSet = new int[314];
protected char curChar;
/** Constructor. */
public VCPU32ParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public VCPU32ParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 157; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = yuxuanchiadm.apc.vcpu32.asm.TokenFactory.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
