/* Generated By:JavaCC: Do not edit this line. VCPU32ParserConstants.java */
package org.apcdevpowered.vcpu32.asm.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VCPU32ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Space = 1;
  /** RegularExpression Id. */
  int Annotate = 2;
  /** RegularExpression Id. */
  int Id = 3;
  /** RegularExpression Id. */
  int Id_Letter = 4;
  /** RegularExpression Id. */
  int Id_Digit = 5;
  /** RegularExpression Id. */
  int Opt = 6;
  /** RegularExpression Id. */
  int Reg = 7;
  /** RegularExpression Id. */
  int Hex = 8;
  /** RegularExpression Id. */
  int Real = 9;
  /** RegularExpression Id. */
  int Dec = 10;
  /** RegularExpression Id. */
  int Oct = 11;
  /** RegularExpression Id. */
  int Bin = 12;
  /** RegularExpression Id. */
  int Char = 13;
  /** RegularExpression Id. */
  int String = 14;
  /** RegularExpression Id. */
  int Label = 15;
  /** RegularExpression Id. */
  int LabelBegin = 16;
  /** RegularExpression Id. */
  int MemBegin = 17;
  /** RegularExpression Id. */
  int MemEnd = 18;
  /** RegularExpression Id. */
  int Comma = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Space>",
    "<Annotate>",
    "<Id>",
    "<Id_Letter>",
    "<Id_Digit>",
    "<Opt>",
    "<Reg>",
    "<Hex>",
    "<Real>",
    "<Dec>",
    "<Oct>",
    "<Bin>",
    "<Char>",
    "<String>",
    "<Label>",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
  };

}
