/* Generated by JTB 1.4.9 */
package yuxuanchiadm.apc.vcpu32.asm.parser.syntaxtree;

/**
 * Represents a token in an ExpansionUnit type 3 in the grammar.<br>
 * If the "-tk" option is used, also contains a ArrayList of preceding special tokens.<br>
 */
public class NodeTCF extends NodeToken {

  /** The serial version UID */
  private static final long serialVersionUID = 149L;

  /**
   * Initializes a {@link NodeTCF} with a given string and no position information.
   *
   * @param s - the token string
   */
  public NodeTCF(String s) {
    super(s, -1, -1, -1, -1, -1);
  }

  /**
   * Initializes a {@link NodeTCF} with a given string and position information.
   *
   * @param s - the token string
   * @param kn - the token kind
   * @param bl - the first line
   * @param bc - the first column
   * @param el - the last line
   * @param ec - the last column
   */
  public NodeTCF(String s, final int kn, final int bl, final int bc, final int el, final int ec) {
    super(s, kn, bl, bc, el, ec);
  }

}
