/* Generated by JTB 1.4.7 */
package yuxuanchiadm.apc.vcpu32.asm.parser.syntaxtree;

import yuxuanchiadm.apc.vcpu32.asm.parser.visitor.*;

/**
 * JTB node class for the production Par:<br>
 * Corresponding grammar:<br>
 * nodeChoice -> . %0 <Dec><br>
 * .......... .. | %1 <Hex><br>
 * .......... .. | %2 <Oct><br>
 * .......... .. | %3 <Bin><br>
 * .......... .. | %4 <Reg><br>
 * .......... .. | %5 #0 <MemBegin><br>
 * .......... .. . .. #1 ( &0 <Reg><br>
 * .......... .. . .. .. | &1 <Dec><br>
 * .......... .. . .. .. | &2 <Hex><br>
 * .......... .. . .. .. | &3 <Oct><br>
 * .......... .. . .. .. | &4 <Bin> )<br>
 * .......... .. . .. #2 <MemEnd><br>
 * .......... .. | %6 <String><br>
 * .......... .. | %7 <Char><br>
 * .......... .. | %8 <Label><br>
 * .......... .. | %9 <Real><br>
 */
@SuppressWarnings("all")
public class Par implements INode {

  /** Child node 1 */
  public NodeChoice nodeChoice;

  /** The serial version UID */
  private static final long serialVersionUID = 147L;

  /**
   * Constructs the node with its child node.
   *
   * @param n0 - the child node
   */
  public Par(final NodeChoice n0) {
    nodeChoice = n0;
  }

  /**
   * Accepts the IRetArguVisitor visitor.
   *
   * @param <R> the user return type
   * @param <A> the user argument type
   * @param vis - the visitor
   * @param argu - a user chosen argument
   * @return a user chosen return information
   */
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  /**
   * Accepts the IRetVisitor visitor.
   *
   * @param <R> the user return type
   * @param vis - the visitor
   * @return a user chosen return information
   */
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  /**
   * Accepts the IVoidArguVisitor visitor.
   *
   * @param <A> the user argument type
   * @param vis - the visitor
   * @param argu - a user chosen argument
   */
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  /**
   * Accepts the IVoidVisitor visitor.
   *
   * @param vis - the visitor
   */
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
